language: C++

compiler: mingw

before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt551 -y
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base qt55multimedia qt55translations qt55tools
 - source /opt/qt55/bin/qt55-env.sh
 - export QTHOME=/opt/qt55
 - sudo apt-get install -qq g++-4.8
 - export CXX="g++-4.8"

script:
 - qmake -project
 - qmake DVS.pro
 - make
