language: C++

sudo: required
dist: trusty

compiler: mingw

before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt551 -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base qt55multimedia qt55translations qt55tools
 - source /opt/qt55/bin/qt55-env.sh
 - export QTHOME=/opt/qt55

script:
 - qmake -project
 - qmake DVS.pro
 - make
