language: cpp

# Ubuntu 14.04 Trusty support
#sudo: required
#dist: trusty

addons:
#  apt:
    #sources:
    # add PPAs with more up-to-date toolchains
    #- ubuntu-toolchain-r-test
    #- llvm-toolchain-precise-3.6
    #packages:
    # install toolchains
    #- gcc-6
    #- g++-6
    #- clang-3.6

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
      env: COMPILER=g++-6

before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt551 -y
# - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base qt55multimedia qt55translations qt55tools
 - source /opt/qt55/bin/qt55-env.sh
 - export QTHOME=/opt/qt55
 #- sudo apt-get install -qq g++-5
 - export CXX="g++-6"
 - export CC="gcc-6"

script:
 - $CXX --version
 - std=c++11
 - qmake -project
 - qmake DVS.pro
 - make
