language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    update-alternatives:
    - install /usr/bin/gcc gcc /usr/bin/gcc-6 50
    - install /usr/bin/g++ g++ /usr/bin/g++-6 50

#install:    
 #- export CXX="g++-6" CC="gcc-6"

before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt551 -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base qt55multimedia qt55translations qt55tools
 - source /opt/qt55/bin/qt55-env.sh
 - export QTHOME=/opt/qt55
 #- sudo apt-get install -qq g++-5

script:
 - g++ --version
 - $CXX --version
 - gcc --version
 - $CC --version
 - qmake -project
 - qmake DVS.pro
 - make --help
 - make CC=gcc-6
