language: C++

before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt551 -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt55base qt55multimedia qt55translations qt55tools
 
script:
 - qmake -project
 - qmake DVS.pro
 - make
